# Generated by Django 5.2.17 on 2026-09-24 00:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalContract',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('reference', models.CharField(help_text='Your contract number, e.g. SC-2026-118', max_length=60)),
                ('vendor', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('oem', 'OEM'), ('third_party', 'Third-party')], default='oem', max_length=20)),
                ('coverage', models.CharField(choices=[('full', 'Full service'), ('parts_labor', 'Parts and labor'), ('parts', 'Parts only'), ('pm_only', 'Preventive maintenance only'), ('tm', 'Time and materials')], default='full', max_length=20)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical contract',
                'verbose_name_plural': 'historical contracts',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reference', models.CharField(help_text='Your contract number, e.g. SC-2026-118', max_length=60)),
                ('vendor', models.CharField(max_length=120)),
                ('type', models.CharField(choices=[('oem', 'OEM'), ('third_party', 'Third-party')], default='oem', max_length=20)),
                ('coverage', models.CharField(choices=[('full', 'Full service'), ('parts_labor', 'Parts and labor'), ('parts', 'Parts only'), ('pm_only', 'Preventive maintenance only'), ('tm', 'Time and materials')], default='full', max_length=20)),
                ('start_on', models.DateField()),
                ('end_on', models.DateField()),
                ('annual_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('notes', models.TextField(blank=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['end_on', 'reference'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'reference'), name='uniq_contract_reference_per_tenant')],
            },
        ),
    ]
