# Generated by Django 5.2.17 on 2026-09-24 00:55

import datetime
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0001_initial'),
        ('equipment', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalWorkOrder',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('type', models.CharField(choices=[('pm', 'Preventive maintenance'), ('repair', 'Corrective repair'), ('inspection', 'Incoming inspection'), ('recall', 'Recall action'), ('safety', 'Safety check')], default='repair', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Entered by staff'), ('portal', 'Service request portal'), ('pm_planner', 'PM planner'), ('recall', 'Recall match')], default='manual', max_length=20)),
                ('requester', models.CharField(blank=True, max_length=120)),
                ('callback', models.CharField(blank=True, help_text='Extension or phone for the requester', max_length=60)),
                ('reported_location', models.CharField(blank=True, max_length=120)),
                ('vendor_service', models.BooleanField(default=False, help_text='Dispatched to the vendor rather than an in-house technician')),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('opened_on', models.DateField(default=datetime.date.today)),
                ('due_on', models.DateField()),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('problem', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('tagged_out', models.BooleanField(default=False, help_text='Requester removed the device from use')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.asset')),
                ('assigned_to', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='credentials.technician')),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical work order',
                'verbose_name_plural': 'historical work orders',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('type', models.CharField(choices=[('pm', 'Preventive maintenance'), ('repair', 'Corrective repair'), ('inspection', 'Incoming inspection'), ('recall', 'Recall action'), ('safety', 'Safety check')], default='repair', max_length=20)),
                ('priority', models.CharField(choices=[('critical', 'Critical'), ('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], default='normal', max_length=10)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('source', models.CharField(choices=[('manual', 'Entered by staff'), ('portal', 'Service request portal'), ('pm_planner', 'PM planner'), ('recall', 'Recall match')], default='manual', max_length=20)),
                ('requester', models.CharField(blank=True, max_length=120)),
                ('callback', models.CharField(blank=True, help_text='Extension or phone for the requester', max_length=60)),
                ('reported_location', models.CharField(blank=True, max_length=120)),
                ('vendor_service', models.BooleanField(default=False, help_text='Dispatched to the vendor rather than an in-house technician')),
                ('vendor_name', models.CharField(blank=True, max_length=120)),
                ('opened_on', models.DateField(default=datetime.date.today)),
                ('due_on', models.DateField()),
                ('started_on', models.DateField(blank=True, null=True)),
                ('completed_on', models.DateField(blank=True, null=True)),
                ('problem', models.TextField()),
                ('resolution', models.TextField(blank=True)),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('tagged_out', models.BooleanField(default=False, help_text='Requester removed the device from use')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='work_orders', to='equipment.asset')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='credentials.technician')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-opened_on', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, max_length=20)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('requester_name', models.CharField(blank=True, max_length=120)),
                ('callback', models.CharField(blank=True, max_length=60)),
                ('problem', models.TextField()),
                ('urgency', models.CharField(choices=[('critical', 'Device unusable and patient care is affected'), ('high', 'Device unusable, a backup is in use'), ('normal', 'Working with a problem, or routine')], default='normal', max_length=10)),
                ('tagged_out', models.BooleanField(default=False)),
                ('submitted_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='equipment.asset')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='equipment.department')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='service_request', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PartLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.CharField(max_length=200)),
                ('part_number', models.CharField(blank=True, max_length=80)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('po_number', models.CharField(blank=True, max_length=40)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_lines', to='workorders.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LaborLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worked_on', models.DateField(default=datetime.date.today)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate', models.DecimalField(decimal_places=2, help_text='Hourly rate applied (in-house or vendor)', max_digits=8)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('technician', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='credentials.technician')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labor_lines', to='workorders.workorder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkOrderNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_name', models.CharField(blank=True, max_length=120)),
                ('text', models.TextField()),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='workorders.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrderStatusHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_status', models.CharField(blank=True, choices=[('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('to_status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In progress'), ('awaiting_parts', 'Awaiting parts'), ('completed', 'Completed'), ('closed', 'Closed'), ('cancelled', 'Cancelled')], max_length=20)),
                ('note', models.CharField(blank=True, max_length=300)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='workorders.workorder')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'status'], name='workorders__tenant__386dfe_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'due_on'], name='workorders__tenant__6bb985_idx'),
        ),
        migrations.AddIndex(
            model_name='workorder',
            index=models.Index(fields=['tenant', 'type', 'completed_on'], name='workorders__tenant__dbe966_idx'),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_wo_number_per_tenant'),
        ),
    ]
