# Generated by Django 5.2.17 on 2026-09-26 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recalls', '0001_initial'),
        ('workorders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='alert',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='The recall or hazard notice this work order responds to', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='recalls.alert'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='alert',
            field=models.ForeignKey(blank=True, help_text='The recall or hazard notice this work order responds to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='work_orders', to='recalls.alert'),
        ),
    ]
