# Generated by Django 5.2.17 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0002_workorder_alert'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicerequest',
            name='requester_email',
            field=models.EmailField(blank=True, help_text='Work email for a confirmation and a done notice (slice 13), at an allowed domain', max_length=254),
        ),
    ]
