# Generated by Django 5.2.17 on 2026-10-05 18:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0004_historicalworkorder_checklist_results_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallaborline',
            name='worked_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='opened_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='laborline',
            name='worked_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='opened_on',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
