# Generated by Django 5.2.17 on 2026-10-06 15:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0001_initial'),
        ('equipment', '0004_devicemodel_oem_schedule_required_and_more'),
        ('recalls', '0001_initial'),
        ('tenants', '0004_facility_time_zone'),
        ('workorders', '0005_alter_historicallaborline_worked_on_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalworkorder',
            name='legacy_number',
            field=models.CharField(blank=True, editable=False, help_text="The work order's number in the previous system, when it was imported", max_length=40, verbose_name='previous number'),
        ),
        migrations.AddField(
            model_name='workorder',
            name='legacy_number',
            field=models.CharField(blank=True, editable=False, help_text="The work order's number in the previous system, when it was imported", max_length=40, verbose_name='previous number'),
        ),
        migrations.AlterField(
            model_name='historicalworkorder',
            name='source',
            field=models.CharField(choices=[('manual', 'Entered by staff'), ('portal', 'Service request portal'), ('pm_planner', 'PM planner'), ('recall', 'Recall match'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='source',
            field=models.CharField(choices=[('manual', 'Entered by staff'), ('portal', 'Service request portal'), ('pm_planner', 'PM planner'), ('recall', 'Recall match'), ('imported', 'Imported')], default='manual', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='workorder',
            constraint=models.UniqueConstraint(condition=models.Q(('legacy_number', ''), _negated=True), fields=('tenant', 'legacy_number'), name='uniq_wo_legacy_number_per_tenant'),
        ),
    ]
