# Generated by Django 5.2.17 on 2026-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorders', '0008_historicalworkorder_inspection_result_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalworkorder',
            name='late_reason',
            field=models.CharField(blank=True, choices=[('device_in_use', 'Device in use, not available'), ('not_located', 'Device could not be located'), ('out_of_service', 'Out of service or in repair when due'), ('waiting_parts_vendor', 'Waiting on parts or the vendor'), ('staffing', 'Staffing or workload'), ('scheduling', 'Scheduling error'), ('duplicate', 'Duplicate work order (the PM was done on another)'), ('incident_hold', 'Held as evidence for an incident investigation'), ('other', "Other (see the work order's notes)")], editable=False, max_length=30, verbose_name='why late'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='late_reason',
            field=models.CharField(blank=True, choices=[('device_in_use', 'Device in use, not available'), ('not_located', 'Device could not be located'), ('out_of_service', 'Out of service or in repair when due'), ('waiting_parts_vendor', 'Waiting on parts or the vendor'), ('staffing', 'Staffing or workload'), ('scheduling', 'Scheduling error'), ('duplicate', 'Duplicate work order (the PM was done on another)'), ('incident_hold', 'Held as evidence for an incident investigation'), ('other', "Other (see the work order's notes)")], editable=False, max_length=30, verbose_name='why late'),
        ),
    ]
