# Generated by Django 5.2.17 on 2026-09-24 00:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source', models.CharField(choices=[('fda', 'FDA'), ('ecri', 'ECRI'), ('mfr', 'Manufacturer letter'), ('other', 'Other')], max_length=10)),
                ('external_id', models.CharField(help_text='e.g. FDA recall number Z-1234-2026 or ECRI accession number', max_length=80)),
                ('classification', models.CharField(blank=True, help_text='Class I, II, III or ECRI priority', max_length=40)),
                ('manufacturer', models.CharField(max_length=160)),
                ('product', models.CharField(help_text='Product description from the notice', max_length=300)),
                ('model_terms', models.JSONField(default=list, help_text='Model names or fragments used to match inventory')),
                ('title', models.CharField(max_length=300)),
                ('action', models.TextField(blank=True)),
                ('url', models.URLField(blank=True)),
                ('published_on', models.DateField(blank=True, null=True)),
                ('raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-published_on'],
                'constraints': [models.UniqueConstraint(fields=('source', 'external_id'), name='uniq_alert_source_id')],
            },
        ),
        migrations.CreateModel(
            name='AlertMatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('needs_action', 'Needs action'), ('under_review', 'Under review'), ('in_progress', 'Action in progress'), ('not_affected', 'Reviewed, not affected'), ('closed', 'Closed')], default='needs_action', max_length=20)),
                ('disposition_note', models.TextField(blank=True)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('alert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='recalls.alert')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_matches', to='equipment.devicemodel')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'alert', 'device_model'), name='uniq_alert_match')],
            },
        ),
    ]
