# Generated by Django 5.2.17 on 2026-09-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='invited_at',
            field=models.DateTimeField(blank=True, help_text='When the latest invitation email was sent; resending replaces the link.', null=True),
        ),
    ]
