# Generated by Django 5.2.17 on 2026-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_invited_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalrole',
            name='scope',
            field=models.CharField(blank=True, choices=[('facility', 'The whole facility'), ('company', 'Only work orders assigned to their company'), ('department', "Only their department's devices and work orders")], help_text='Which devices and work orders its users see; blank takes the default for the role (DEFAULT_SCOPES)', max_length=20),
        ),
        migrations.AddField(
            model_name='role',
            name='scope',
            field=models.CharField(blank=True, choices=[('facility', 'The whole facility'), ('company', 'Only work orders assigned to their company'), ('department', "Only their department's devices and work orders")], help_text='Which devices and work orders its users see; blank takes the default for the role (DEFAULT_SCOPES)', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='company',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
