# Generated by Django 5.2.17 on 2026-10-05 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_historicalrole_scope_role_scope_user_company'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(choices=[('invited', 'Invited'), ('invitation_resent', 'Invitation resent'), ('role_changed', 'Role changed'), ('scope_changed', 'Company or unit changed'), ('deactivated', 'Deactivated'), ('reactivated', 'Reactivated'), ('role_created', 'Role added'), ('role_level_changed', 'Role access changed'), ('role_scope_changed', 'What a role sees changed')], max_length=30)),
                ('detail', models.CharField(blank=True, help_text="What changed, in words: 'Technician → CE manager', 'Contracts: View → Edit'", max_length=300)),
                ('by', models.ForeignKey(blank=True, help_text='Who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('role', models.ForeignKey(blank=True, help_text='Which role changed, or was given', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.role')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(blank=True, help_text='Whose account changed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-at'],
                'indexes': [models.Index(fields=['tenant', 'at'], name='accounts_ac_tenant__a62ba8_idx')],
            },
        ),
    ]
