# Generated by Django 5.2.17 on 2026-10-06 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_accessevent'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('tenants', '0004_facility_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='person',
            field=models.UUIDField(blank=True, editable=False, help_text='Accounts of one person in several facilities share this; empty for an account in one facility.', null=True),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(fields=('person', 'tenant'), name='uniq_person_per_facility'),
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.CheckConstraint(condition=models.Q(('person__isnull', True), ('tenant__isnull', False), _connector='OR'), name='person_needs_facility'),
        ),
    ]
