# Generated by Django 5.2.17 on 2026-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_user_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='module',
            field=models.CharField(choices=[('equipment', 'Equipment'), ('workorders', 'Work orders'), ('pm', 'PM schedule'), ('contracts', 'Contracts'), ('recalls', 'Recalls'), ('reports', 'Reports'), ('users', 'Users and access'), ('settings', 'Settings'), ('incidents', 'Incidents')], max_length=20),
        ),
    ]
