# Generated by Django 5.2.17 on 2026-09-29 13:43

import django.db.models.deletion
import simple_history.models
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalFacilitySettings',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('portal_require_callback', models.BooleanField(default=True, help_text='Requesters must give a callback number')),
                ('portal_hotline', models.CharField(blank=True, help_text='Shown to requesters on the portal, e.g. ext. 4400', max_length=40)),
                ('policy_life_support', models.CharField(default='OEM interval, complete within due month, no grace', max_length=300)),
                ('policy_medium_low', models.CharField(default='AEM allowed, 30-day grace after due month', max_length=300)),
                ('policy_aem', models.CharField(default='Equipment Management Committee, 3-year failure history required', max_length=300)),
                ('policy_missing', models.CharField(default='Escalate after 2 search attempts; report monthly', max_length=300)),
                ('policy_incoming', models.CharField(default='Required before first clinical use, electrical safety per IEC 62353', max_length=300)),
                ('policy_post_repair', models.CharField(default='Safety test required before return to service', max_length=300)),
                ('policy_assignment', models.CharField(default='Credentialed technicians first; overrides are flagged on the work order', max_length=300)),
                ('policy_portal', models.CharField(default='Triage within 30 minutes during shop hours', max_length=300)),
                ('target_pm_pct', models.DecimalField(decimal_places=1, default=Decimal('95.0'), help_text='PM completion target for medium and low risk equipment; life support and high risk are held at 100%', max_digits=4)),
                ('target_uptime_pct', models.DecimalField(decimal_places=2, default=Decimal('99.50'), max_digits=5)),
                ('target_mttr_days', models.DecimalField(decimal_places=1, default=Decimal('3.0'), max_digits=4)),
                ('repair_budget_monthly', models.DecimalField(blank=True, decimal_places=2, help_text="Monthly repair budget shown on the Overview's spend tile; blank for none", max_digits=12, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical facility settings',
                'verbose_name_plural': 'historical facility settings',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='FacilitySettings',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portal_require_callback', models.BooleanField(default=True, help_text='Requesters must give a callback number')),
                ('portal_hotline', models.CharField(blank=True, help_text='Shown to requesters on the portal, e.g. ext. 4400', max_length=40)),
                ('policy_life_support', models.CharField(default='OEM interval, complete within due month, no grace', max_length=300)),
                ('policy_medium_low', models.CharField(default='AEM allowed, 30-day grace after due month', max_length=300)),
                ('policy_aem', models.CharField(default='Equipment Management Committee, 3-year failure history required', max_length=300)),
                ('policy_missing', models.CharField(default='Escalate after 2 search attempts; report monthly', max_length=300)),
                ('policy_incoming', models.CharField(default='Required before first clinical use, electrical safety per IEC 62353', max_length=300)),
                ('policy_post_repair', models.CharField(default='Safety test required before return to service', max_length=300)),
                ('policy_assignment', models.CharField(default='Credentialed technicians first; overrides are flagged on the work order', max_length=300)),
                ('policy_portal', models.CharField(default='Triage within 30 minutes during shop hours', max_length=300)),
                ('target_pm_pct', models.DecimalField(decimal_places=1, default=Decimal('95.0'), help_text='PM completion target for medium and low risk equipment; life support and high risk are held at 100%', max_digits=4)),
                ('target_uptime_pct', models.DecimalField(decimal_places=2, default=Decimal('99.50'), max_digits=5)),
                ('target_mttr_days', models.DecimalField(decimal_places=1, default=Decimal('3.0'), max_digits=4)),
                ('repair_budget_monthly', models.DecimalField(blank=True, decimal_places=2, help_text="Monthly repair budget shown on the Overview's spend tile; blank for none", max_digits=12, null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'facility settings',
                'verbose_name_plural': 'facility settings',
                'constraints': [models.UniqueConstraint(fields=('tenant',), name='uniq_facility_settings_per_tenant')],
            },
        ),
    ]
