# Generated by Django 5.2.17 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysettings',
            name='portal_confirmation',
            field=models.CharField(choices=[('screen', 'On screen'), ('email', 'On screen and by email')], default='screen', max_length=10),
        ),
        migrations.AddField(
            model_name='facilitysettings',
            name='portal_email_domains',
            field=models.CharField(blank=True, help_text='Work email domains the portal may email, comma-separated', max_length=200),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='portal_confirmation',
            field=models.CharField(choices=[('screen', 'On screen'), ('email', 'On screen and by email')], default='screen', max_length=10),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='portal_email_domains',
            field=models.CharField(blank=True, help_text='Work email domains the portal may email, comma-separated', max_length=200),
        ),
    ]
