# Generated by Django 5.2.17 on 2026-10-02 11:39

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0002_facilitysettings_portal_confirmation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysettings',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('82.00'), help_text='In-house labor, per hour', max_digits=8),
        ),
        migrations.AddField(
            model_name='facilitysettings',
            name='vendor_labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('215.00'), help_text='Vendor service labor, per hour', max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('82.00'), help_text='In-house labor, per hour', max_digits=8),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='vendor_labor_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('215.00'), help_text='Vendor service labor, per hour', max_digits=8),
        ),
    ]
