# Generated by Django 5.2.17 on 2026-10-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0003_facilitysettings_labor_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysettings',
            name='technicians_take_work',
            field=models.BooleanField(default=True, help_text='Technicians may take unassigned work they are credentialed for', verbose_name='technicians may take unassigned work'),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='technicians_take_work',
            field=models.BooleanField(default=True, help_text='Technicians may take unassigned work they are credentialed for', verbose_name='technicians may take unassigned work'),
        ),
    ]
