# Generated by Django 5.2.17 on 2026-10-07 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0004_facilitysettings_technicians_take_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facilitysettings',
            name='policy_life_support',
            field=models.CharField(default='OEM interval, complete by the due date, no grace', max_length=300),
        ),
        migrations.AlterField(
            model_name='facilitysettings',
            name='policy_medium_low',
            field=models.CharField(default='AEM allowed, complete by the due date', max_length=300),
        ),
        migrations.AlterField(
            model_name='historicalfacilitysettings',
            name='policy_life_support',
            field=models.CharField(default='OEM interval, complete by the due date, no grace', max_length=300),
        ),
        migrations.AlterField(
            model_name='historicalfacilitysettings',
            name='policy_medium_low',
            field=models.CharField(default='AEM allowed, complete by the due date', max_length=300),
        ),
    ]
