# Generated by Django 5.2.17 on 2026-10-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facility', '0005_alter_facilitysettings_policy_life_support_and_more'),
        ('tenants', '0004_facility_time_zone'),
    ]

    operations = [
        migrations.AddField(
            model_name='facilitysettings',
            name='pm_window_high',
            field=models.CharField(choices=[('due_date', 'By the due date'), ('days_after', 'Within a number of days after the due date'), ('due_month', 'By the end of the due month'), ('next_month', 'By the end of the month after the due month')], default='due_date', max_length=20, verbose_name='PM on time, life support and high risk'),
        ),
        migrations.AddField(
            model_name='facilitysettings',
            name='pm_window_high_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PM on time, life support and high risk: days after the due date'),
        ),
        migrations.AddField(
            model_name='facilitysettings',
            name='pm_window_other',
            field=models.CharField(choices=[('due_date', 'By the due date'), ('days_after', 'Within a number of days after the due date'), ('due_month', 'By the end of the due month'), ('next_month', 'By the end of the month after the due month')], default='due_date', max_length=20, verbose_name='PM on time, medium and low risk'),
        ),
        migrations.AddField(
            model_name='facilitysettings',
            name='pm_window_other_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PM on time, medium and low risk: days after the due date'),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='pm_window_high',
            field=models.CharField(choices=[('due_date', 'By the due date'), ('days_after', 'Within a number of days after the due date'), ('due_month', 'By the end of the due month'), ('next_month', 'By the end of the month after the due month')], default='due_date', max_length=20, verbose_name='PM on time, life support and high risk'),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='pm_window_high_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PM on time, life support and high risk: days after the due date'),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='pm_window_other',
            field=models.CharField(choices=[('due_date', 'By the due date'), ('days_after', 'Within a number of days after the due date'), ('due_month', 'By the end of the due month'), ('next_month', 'By the end of the month after the due month')], default='due_date', max_length=20, verbose_name='PM on time, medium and low risk'),
        ),
        migrations.AddField(
            model_name='historicalfacilitysettings',
            name='pm_window_other_days',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='PM on time, medium and low risk: days after the due date'),
        ),
        migrations.AddConstraint(
            model_name='facilitysettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pm_window_high', 'days_after'), ('pm_window_high_days__gte', 1), ('pm_window_high_days__isnull', False), ('pm_window_high_days__lte', 45)), models.Q(models.Q(('pm_window_high', 'days_after'), _negated=True), ('pm_window_high_days__isnull', True)), _connector='OR'), name='pm_window_high_days'),
        ),
        migrations.AddConstraint(
            model_name='facilitysettings',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('pm_window_other', 'days_after'), ('pm_window_other_days__gte', 1), ('pm_window_other_days__isnull', False), ('pm_window_other_days__lte', 45)), models.Q(models.Q(('pm_window_other', 'days_after'), _negated=True), ('pm_window_other_days__isnull', True)), _connector='OR'), name='pm_window_other_days'),
        ),
    ]
