# Generated by Django 5.2.17 on 2026-10-05 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('tenants', '0002_alter_tenant_timezone_historicaltenant'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='jobrun',
            name='uniq_job_run_per_day',
        ),
        migrations.AddField(
            model_name='jobrun',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant'),
        ),
        migrations.AlterField(
            model_name='jobrun',
            name='run_on',
            field=models.DateField(help_text="The local day this run is for (the facility's, for a facility's run)"),
        ),
        migrations.AddConstraint(
            model_name='jobrun',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', True)), fields=('job', 'run_on'), name='uniq_job_run_per_day'),
        ),
        migrations.AddConstraint(
            model_name='jobrun',
            constraint=models.UniqueConstraint(condition=models.Q(('facility__isnull', False)), fields=('job', 'facility', 'run_on'), name='uniq_job_run_per_facility_day'),
        ),
    ]
