# Generated by Django 5.2.17 on 2026-09-24 00:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('pm', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('cost_center', models.CharField(blank=True, max_length=40)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('description', models.CharField(help_text="Plain-language device name, e.g. 'Infusion pump'", max_length=200)),
                ('category', models.CharField(help_text="Product category, e.g. 'Infusion pumps'", max_length=80)),
                ('risk_class', models.CharField(choices=[('life_support', 'Life support'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('oem_pm_interval_months', models.PositiveSmallIntegerField(default=12)),
                ('aem_interval_months', models.PositiveSmallIntegerField(blank=True, help_text='Approved alternative equipment maintenance interval; blank = follow OEM', null=True)),
                ('expected_life_years', models.PositiveSmallIntegerField(default=8)),
                ('list_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('pm_procedure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='device_models', to='pm.pmprocedure')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['manufacturer', 'model'],
            },
        ),
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tag', models.CharField(help_text='Control number on the CE sticker, e.g. CE-10241', max_length=40)),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('in_repair', 'In repair'), ('out_of_service', 'Out of service'), ('on_loan', 'On loan'), ('missing', 'Missing'), ('retired', 'Retired')], default='in_service', max_length=20)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.PositiveSmallIntegerField(default=3, help_text='1 (poor) to 5 (excellent)')),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('support_type', models.CharField(choices=[('in_house', 'In-house'), ('oem_contract', 'OEM contract'), ('third_party', 'Third-party')], default='in_house', editable=False, max_length=20)),
                ('last_pm_on', models.DateField(blank=True, null=True)),
                ('next_pm_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('contract', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets', to='contracts.contract')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='equipment.department')),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='equipment.devicemodel')),
            ],
            options={
                'ordering': ['tag'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalAsset',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('tag', models.CharField(help_text='Control number on the CE sticker, e.g. CE-10241', max_length=40)),
                ('serial', models.CharField(blank=True, max_length=80)),
                ('room', models.CharField(blank=True, max_length=40)),
                ('status', models.CharField(choices=[('in_service', 'In service'), ('in_repair', 'In repair'), ('out_of_service', 'Out of service'), ('on_loan', 'On loan'), ('missing', 'Missing'), ('retired', 'Retired')], default='in_service', max_length=20)),
                ('installed_on', models.DateField(blank=True, null=True)),
                ('acquisition_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('condition', models.PositiveSmallIntegerField(default=3, help_text='1 (poor) to 5 (excellent)')),
                ('warranty_end', models.DateField(blank=True, null=True)),
                ('support_type', models.CharField(choices=[('in_house', 'In-house'), ('oem_contract', 'OEM contract'), ('third_party', 'Third-party')], default='in_house', editable=False, max_length=20)),
                ('last_pm_on', models.DateField(blank=True, null=True)),
                ('next_pm_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('contract', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='contracts.contract')),
                ('department', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.department')),
                ('device_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.devicemodel')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical asset',
                'verbose_name_plural': 'historical assets',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalDeviceModel',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('manufacturer', models.CharField(max_length=120)),
                ('model', models.CharField(max_length=120)),
                ('description', models.CharField(help_text="Plain-language device name, e.g. 'Infusion pump'", max_length=200)),
                ('category', models.CharField(help_text="Product category, e.g. 'Infusion pumps'", max_length=80)),
                ('risk_class', models.CharField(choices=[('life_support', 'Life support'), ('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', max_length=20)),
                ('oem_pm_interval_months', models.PositiveSmallIntegerField(default=12)),
                ('aem_interval_months', models.PositiveSmallIntegerField(blank=True, help_text='Approved alternative equipment maintenance interval; blank = follow OEM', null=True)),
                ('expected_life_years', models.PositiveSmallIntegerField(default=8)),
                ('list_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('pm_procedure', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pm.pmprocedure')),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical device model',
                'verbose_name_plural': 'historical device models',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.AddConstraint(
            model_name='department',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_department_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='devicemodel',
            constraint=models.UniqueConstraint(fields=('tenant', 'manufacturer', 'model'), name='uniq_model_per_tenant'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'status'], name='equipment_a_tenant__57d1ec_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['tenant', 'next_pm_on'], name='equipment_a_tenant__cbcc14_idx'),
        ),
        migrations.AddConstraint(
            model_name='asset',
            constraint=models.UniqueConstraint(fields=('tenant', 'tag'), name='uniq_tag_per_tenant'),
        ),
    ]
