# Generated by Django 5.2.17 on 2026-09-28 19:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asset',
            name='tag',
            field=models.CharField(help_text='Control number on the CE sticker, e.g. CE-10241', max_length=40, validators=[django.core.validators.RegexValidator('^[^\\s/]+$', 'Asset tags cannot contain spaces or slashes.')]),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='tag',
            field=models.CharField(help_text='Control number on the CE sticker, e.g. CE-10241', max_length=40, validators=[django.core.validators.RegexValidator('^[^\\s/]+$', 'Asset tags cannot contain spaces or slashes.')]),
        ),
    ]
