# Generated by Django 5.2.17 on 2026-10-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0002_asset_tag_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='risk_function',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Clinical function, 1 to 10', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='risk_incidents',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Incident history, 0 to 2', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='risk_maintenance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maintenance requirement, 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='risk_physical',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Physical risk of failure, 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='devicemodel',
            name='risk_reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='risk_function',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Clinical function, 1 to 10', null=True),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='risk_incidents',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Incident history, 0 to 2', null=True),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='risk_maintenance',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Maintenance requirement, 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='risk_physical',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Physical risk of failure, 1 to 5', null=True),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='risk_reviewed_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
