# Generated by Django 5.2.17 on 2026-10-02 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_devicemodel_risk_function_devicemodel_risk_incidents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicemodel',
            name='oem_schedule_required',
            field=models.BooleanField(default=False, help_text="Imaging, radiologic, or medical laser equipment: CMS requires the manufacturer's maintenance schedule, so it never goes on AEM"),
        ),
        migrations.AddField(
            model_name='historicaldevicemodel',
            name='oem_schedule_required',
            field=models.BooleanField(default=False, help_text="Imaging, radiologic, or medical laser equipment: CMS requires the manufacturer's maintenance schedule, so it never goes on AEM"),
        ),
    ]
