# Generated by Django 5.2.17 on 2026-10-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0004_devicemodel_oem_schedule_required_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='added_as',
            field=models.CharField(blank=True, choices=[('new', 'New to the facility'), ('existing', 'Already in use here'), ('imported', 'Imported from the previous system')], editable=False, help_text='How the device came to be in Cadence (create_asset): new, already in use, or imported', max_length=20),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='added_as',
            field=models.CharField(blank=True, choices=[('new', 'New to the facility'), ('existing', 'Already in use here'), ('imported', 'Imported from the previous system')], editable=False, help_text='How the device came to be in Cadence (create_asset): new, already in use, or imported', max_length=20),
        ),
    ]
