# Generated by Django 5.2.17 on 2026-10-07 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0005_asset_added_as_historicalasset_added_as'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='awaiting_inspection',
            field=models.BooleanField(default=False, editable=False, help_text='New, and waiting for its incoming inspection before first use'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='awaiting_inspection',
            field=models.BooleanField(default=False, editable=False, help_text='New, and waiting for its incoming inspection before first use'),
        ),
    ]
