# Generated by Django 5.2.17 on 2026-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0006_asset_awaiting_inspection_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='incident_hold',
            field=models.BooleanField(default=False, editable=False, help_text='Held as evidence for an incident investigation'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='incident_hold',
            field=models.BooleanField(default=False, editable=False, help_text='Held as evidence for an incident investigation'),
        ),
    ]
