# Generated by Django 5.2.17 on 2026-10-09 15:56

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0007_asset_incident_hold_historicalasset_incident_hold'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='arrived_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='due_back_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='kept_on',
            field=models.DateField(blank=True, editable=False, help_text='The facility kept (bought) it: ours from that day', null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner',
            field=models.CharField(blank=True, editable=False, help_text='The company that owns a temporary device', max_length=120),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_pm_due_on',
            field=models.DateField(blank=True, editable=False, help_text="The owner's PM date, from its sticker", null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='owner_reference',
            field=models.CharField(blank=True, editable=False, help_text="The rental agreement, PO, or RMA number (never a patient's name or record number)", max_length=40, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/#-]*$', "Enter the agreement, PO, or RMA number as the owner's paperwork shows it, without spaces.")]),
        ),
        migrations.AddField(
            model_name='asset',
            name='ownership',
            field=models.CharField(choices=[('owned', 'Ours'), ('rental', 'Rental'), ('loaner', 'Vendor loaner'), ('demo', 'Demo or evaluation unit')], default='owned', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_cleaning',
            field=models.CharField(blank=True, choices=[('decontaminated', 'Cleaned and decontaminated'), ('labeled', 'Parts still contaminated are labeled'), ('not_in_hand', 'Not in hand: lost, settled with its owner')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='return_data',
            field=models.CharField(blank=True, choices=[('cleared', 'Patient data cleared'), ('none_stored', 'Stores no patient data'), ('not_applicable', 'Not applicable')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='asset',
            name='returned_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='stands_in_for',
            field=models.ForeignKey(blank=True, editable=False, help_text='The device of ours a vendor loaner stands in for', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='loaners', to='equipment.asset'),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='arrived_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='due_back_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='kept_on',
            field=models.DateField(blank=True, editable=False, help_text='The facility kept (bought) it: ours from that day', null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='owner',
            field=models.CharField(blank=True, editable=False, help_text='The company that owns a temporary device', max_length=120),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='owner_pm_due_on',
            field=models.DateField(blank=True, editable=False, help_text="The owner's PM date, from its sticker", null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='owner_reference',
            field=models.CharField(blank=True, editable=False, help_text="The rental agreement, PO, or RMA number (never a patient's name or record number)", max_length=40, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/#-]*$', "Enter the agreement, PO, or RMA number as the owner's paperwork shows it, without spaces.")]),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='ownership',
            field=models.CharField(choices=[('owned', 'Ours'), ('rental', 'Rental'), ('loaner', 'Vendor loaner'), ('demo', 'Demo or evaluation unit')], default='owned', editable=False, max_length=10),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='return_cleaning',
            field=models.CharField(blank=True, choices=[('decontaminated', 'Cleaned and decontaminated'), ('labeled', 'Parts still contaminated are labeled'), ('not_in_hand', 'Not in hand: lost, settled with its owner')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='return_data',
            field=models.CharField(blank=True, choices=[('cleared', 'Patient data cleared'), ('none_stored', 'Stores no patient data'), ('not_applicable', 'Not applicable')], editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='returned_on',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='historicalasset',
            name='stands_in_for',
            field=models.ForeignKey(blank=True, db_constraint=False, editable=False, help_text='The device of ours a vendor loaner stands in for', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.asset'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='support_type',
            field=models.CharField(choices=[('in_house', 'In-house'), ('oem_contract', 'OEM contract'), ('third_party', 'Third-party'), ('owner', 'Owner maintains')], default='in_house', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='historicalasset',
            name='support_type',
            field=models.CharField(choices=[('in_house', 'In-house'), ('oem_contract', 'OEM contract'), ('third_party', 'Third-party'), ('owner', 'Owner maintains')], default='in_house', editable=False, max_length=20),
        ),
    ]
