# Generated by Django 5.2.17 on 2026-09-24 00:55

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPmProcedure',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('code', models.CharField(help_text='Short code, e.g. PH-MX750-PM12', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('source_kind', models.CharField(choices=[('oem', 'OEM service manual'), ('ecri', 'ECRI generic IPM'), ('in_house', 'In-house')], default='oem', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Manual title and revision, or ECRI procedure number', max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Deep link, e.g. to the oneSOURCE document')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('checklist', models.JSONField(default=list, help_text='Ordered list of steps; each step is a string or {"text": ..., "measure": ...}')),
                ('revision', models.CharField(blank=True, max_length=40)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical pm procedure',
                'verbose_name_plural': 'historical pm procedures',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='PmProcedure',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text='Short code, e.g. PH-MX750-PM12', max_length=40)),
                ('name', models.CharField(max_length=200)),
                ('source_kind', models.CharField(choices=[('oem', 'OEM service manual'), ('ecri', 'ECRI generic IPM'), ('in_house', 'In-house')], default='oem', max_length=20)),
                ('source_reference', models.CharField(blank=True, help_text='Manual title and revision, or ECRI procedure number', max_length=200)),
                ('source_url', models.URLField(blank=True, help_text='Deep link, e.g. to the oneSOURCE document')),
                ('estimated_hours', models.DecimalField(decimal_places=2, default=1, max_digits=5)),
                ('checklist', models.JSONField(default=list, help_text='Ordered list of steps; each step is a string or {"text": ..., "measure": ...}')),
                ('revision', models.CharField(blank=True, max_length=40)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['code'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'code'), name='uniq_pm_procedure_code_per_tenant')],
            },
        ),
    ]
