# Generated by Django 5.2.17 on 2026-10-01 20:05

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0003_devicemodel_risk_function_devicemodel_risk_incidents_and_more'),
        ('pm', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalAemDecision',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('interval_months', models.PositiveSmallIntegerField(help_text='The proposed PM interval')),
                ('oem_interval_months', models.PositiveSmallIntegerField(help_text='The OEM interval when proposed')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ended', 'Ended')], default='proposed', max_length=20)),
                ('rationale', models.TextField(help_text='The case for the change, from the proposer')),
                ('evidence', models.JSONField(default=dict, help_text="The model's failure history as the proposal saw it (apps.pm.aem.evidence)")),
                ('proposed_on', models.DateField()),
                ('decided_on', models.DateField(blank=True, help_text="The committee's meeting date (approved or rejected)", null=True)),
                ('decision_note', models.TextField(blank=True, help_text="The committee's minutes reference or reason")),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=300)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('decided_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.devicemodel')),
                ('ended_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical aem decision',
                'verbose_name_plural': 'historical aem decisions',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='AemDecision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_months', models.PositiveSmallIntegerField(help_text='The proposed PM interval')),
                ('oem_interval_months', models.PositiveSmallIntegerField(help_text='The OEM interval when proposed')),
                ('status', models.CharField(choices=[('proposed', 'Proposed'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('withdrawn', 'Withdrawn'), ('ended', 'Ended')], default='proposed', max_length=20)),
                ('rationale', models.TextField(help_text='The case for the change, from the proposer')),
                ('evidence', models.JSONField(default=dict, help_text="The model's failure history as the proposal saw it (apps.pm.aem.evidence)")),
                ('proposed_on', models.DateField()),
                ('decided_on', models.DateField(blank=True, help_text="The committee's meeting date (approved or rejected)", null=True)),
                ('decision_note', models.TextField(blank=True, help_text="The committee's minutes reference or reason")),
                ('ended_on', models.DateField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=300)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('device_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aem_decisions', to='equipment.devicemodel')),
                ('ended_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('proposed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-proposed_on', '-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'proposed')), fields=('tenant', 'device_model'), name='uniq_open_aem_proposal_per_model'), models.UniqueConstraint(condition=models.Q(('status', 'approved')), fields=('tenant', 'device_model'), name='uniq_aem_in_force_per_model')],
            },
        ),
    ]
