# Generated by Django 5.2.17 on 2026-10-05 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_alter_tenant_timezone_historicaltenant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaltenant',
            name='timezone',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='timezone',
        ),
    ]
