# Generated by Django 5.2.17 on 2026-10-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_drop_unused_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltenant',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="The facility's IANA time zone; blank uses the server's (DJANGO_TIME_ZONE)", max_length=64),
        ),
        migrations.AddField(
            model_name='tenant',
            name='timezone',
            field=models.CharField(blank=True, default='', help_text="The facility's IANA time zone; blank uses the server's (DJANGO_TIME_ZONE)", max_length=64),
        ),
    ]
