# Generated by Django 5.2.17 on 2026-10-01 19:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('report', models.CharField(help_text='A key of apps.reports.services.REPORTS', max_length=20)),
                ('frequency', models.CharField(choices=[('weekly', 'Every Monday'), ('monthly', 'First Monday of each month')], max_length=10)),
                ('last_sent_on', models.DateField(blank=True, help_text='The local day it was last emailed; a day is never sent twice', null=True)),
                ('start_on', models.DateField(blank=True, help_text='The first sending day it may send for (set when it is turned on)', null=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['report'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user', 'report'), name='uniq_report_subscription_per_user')],
            },
        ),
    ]
