# Generated by Django 5.2.17 on 2026-10-02 19:32

import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportsubscription',
            name='report',
            field=models.CharField(help_text="A key of apps.reports.services.REPORTS, or a custom report's (custom-<id>)", max_length=50),
        ),
        migrations.CreateModel(
            name='HistoricalCustomReport',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('name', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('work_orders', 'Work orders'), ('devices', 'Devices'), ('labor', 'Labor (time logged)'), ('parts', 'Parts used')], max_length=20)),
                ('columns', models.JSONField(default=list, help_text='Column keys of the source, in the order shown')),
                ('filters', models.JSONField(default=dict, help_text='Filter key to value, as apps.reports.custom declares them for the source')),
                ('group_by', models.CharField(blank=True, help_text='A column key the source can group by; blank lists the rows', max_length=40)),
                ('sort', models.CharField(blank=True, help_text="A column key, with a leading '-' for descending; blank is the source's order", max_length=41)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'historical custom report',
                'verbose_name_plural': 'historical custom reports',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='CustomReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=80)),
                ('source', models.CharField(choices=[('work_orders', 'Work orders'), ('devices', 'Devices'), ('labor', 'Labor (time logged)'), ('parts', 'Parts used')], max_length=20)),
                ('columns', models.JSONField(default=list, help_text='Column keys of the source, in the order shown')),
                ('filters', models.JSONField(default=dict, help_text='Filter key to value, as apps.reports.custom declares them for the source')),
                ('group_by', models.CharField(blank=True, help_text='A column key the source can group by; blank lists the rows', max_length=40)),
                ('sort', models.CharField(blank=True, help_text="A column key, with a leading '-' for descending; blank is the source's order", max_length=41)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'name'), name='uniq_custom_report_name_per_tenant')],
            },
        ),
    ]
