# Generated by Django 5.2.17 on 2026-10-06 15:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0004_facility_time_zone'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(help_text='Which importer reads the file (apps.imports.kinds)', max_length=30)),
                ('file_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('mapping', 'Choosing columns'), ('checking', 'Checking'), ('checked', 'Checked'), ('importing', 'Importing'), ('imported', 'Imported'), ('discarded', 'Discarded'), ('expired', 'Expired')], default='mapping', max_length=20)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('imported_at', models.DateTimeField(blank=True, null=True)),
                ('header', models.JSONField(blank=True, default=list, help_text="The file's column names, as written")),
                ('columns', models.JSONField(blank=True, default=list, help_text="Once confirmed: the importer's column keys, in the order rows hold them")),
                ('rows', models.JSONField(blank=True, default=list, help_text="The file's rows (lists of cells); cleared when the run ends")),
                ('row_count', models.PositiveIntegerField(default=0)),
                ('offset', models.PositiveIntegerField(default=0, help_text='Rows done by the current pass (the check, or the import)')),
                ('file_problems', models.JSONField(blank=True, default=dict, help_text='Row index -> why the whole row is refused (a repeat in the file)')),
                ('results', models.JSONField(blank=True, default=list, help_text='[line, key, outcome, [notes]] for every row with a note or skipped')),
                ('counts', models.JSONField(blank=True, default=dict, help_text='Outcome -> rows, for the current pass')),
                ('summary', models.JSONField(blank=True, default=dict, help_text="The importer's totals, new names, and value mappings")),
                ('imported_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'importing')), fields=('tenant',), name='one_import_running_per_facility')],
            },
        ),
    ]
