# Generated by Django 5.2.17 on 2026-10-08 17:39

import django.core.validators
import django.db.models.deletion
import simple_history.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0007_asset_incident_hold_historicalasset_incident_hold'),
        ('tenants', '0004_facility_time_zone'),
        ('workorders', '0009_alter_historicalworkorder_late_reason_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalIncident',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('number', models.CharField(editable=False, help_text="IN-26-0004 (Sequence 'incident-<yy>')", max_length=20)),
                ('opened_work_order', models.BooleanField(default=False, help_text='The incident opened its work order (else it adopted an open one)')),
                ('occurred_on', models.DateField()),
                ('aware_on', models.DateField(help_text="When the facility's clinical staff first knew: the 10-work-day clock starts the day after")),
                ('outcome', models.CharField(choices=[('death', 'Death'), ('serious_injury', 'Serious injury or illness (life-threatening, permanent damage, or needed treatment to prevent it)'), ('unknown', 'Not known yet (treated as serious until decided)'), ('injury', 'Injury, not serious'), ('no_harm', 'No harm (malfunction or near miss)')], max_length=20)),
                ('affected', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff member on duty'), ('other', 'Visitor or another person'), ('none', 'No one')], max_length=10)),
                ('event_reference', models.CharField(blank=True, help_text="The number in the facility's event reporting system, where the narrative and the deliberations are", max_length=40, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/#-]*$', "Enter the event report's number as your event reporting system shows it, without spaces.")])),
                ('report_due_on', models.DateField(blank=True, editable=False, help_text='The 10th work day after aware_on while the incident has a clock (services only)', null=True)),
                ('reportable', models.BooleanField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, choices=[('may_have', 'The information reasonably suggests the device may have caused or contributed (use error included), or it cannot be ruled out'), ('not_serious', 'Not a death or serious injury as 21 CFR 803 defines it'), ('no_suggestion', 'The information does not suggest the device caused or contributed'), ('not_patient', 'The person was not a patient of the facility or staff on duty')], max_length=20)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, choices=[('risk', 'Risk management or patient safety'), ('committee', 'A safety or MDR committee'), ('ce', 'Clinical Engineering')], max_length=20)),
                ('fda_reported_on', models.DateField(blank=True, null=True)),
                ('manufacturer_reported_on', models.DateField(blank=True, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}-\\d{4}-\\d{4}$', "Enter the report number as 21 CFR 803 forms it: the facility's 10-digit number, the year, and a 4-digit sequence (0123456789-2026-0001).")])),
                ('finding', models.CharField(blank=True, choices=[('device_failure', 'Device failure or malfunction found'), ('accessory_failure', 'Failure found in an accessory, disposable, or connected device'), ('utility', 'A power, medical gas, or other utility problem found'), ('met_specs', 'The device met its specifications (no device fault found)'), ('manufacturer', 'Evaluated by the manufacturer'), ('not_evaluated', 'Could not be evaluated')], max_length=20)),
                ('accessories', models.CharField(blank=True, choices=[('kept', 'Kept with the device'), ('none_used', 'None were in use'), ('not_available', 'Not available (discarded or lost)')], help_text='The disposables and accessories in use, kept with the device as evidence', max_length=20)),
                ('event_log', models.CharField(blank=True, choices=[('saved', 'Saved'), ('no_log', 'The device keeps no log'), ('lost', 'Lost or could not be retrieved')], help_text="The device's event log", max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_error', 'Recorded in error')], default='open', max_length=10)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, help_text='The device suspected', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.asset')),
                ('closed_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, db_constraint=False, help_text='Who recorded the decision in Cadence', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(blank=True, db_constraint=False, help_text='The investigation: the request it was reported as (adopted), or one the incident opened', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='workorders.workorder')),
            ],
            options={
                'verbose_name': 'historical incident',
                'verbose_name_plural': 'historical incidents',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('number', models.CharField(editable=False, help_text="IN-26-0004 (Sequence 'incident-<yy>')", max_length=20)),
                ('opened_work_order', models.BooleanField(default=False, help_text='The incident opened its work order (else it adopted an open one)')),
                ('occurred_on', models.DateField()),
                ('aware_on', models.DateField(help_text="When the facility's clinical staff first knew: the 10-work-day clock starts the day after")),
                ('outcome', models.CharField(choices=[('death', 'Death'), ('serious_injury', 'Serious injury or illness (life-threatening, permanent damage, or needed treatment to prevent it)'), ('unknown', 'Not known yet (treated as serious until decided)'), ('injury', 'Injury, not serious'), ('no_harm', 'No harm (malfunction or near miss)')], max_length=20)),
                ('affected', models.CharField(choices=[('patient', 'Patient'), ('staff', 'Staff member on duty'), ('other', 'Visitor or another person'), ('none', 'No one')], max_length=10)),
                ('event_reference', models.CharField(blank=True, help_text="The number in the facility's event reporting system, where the narrative and the deliberations are", max_length=40, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9][A-Za-z0-9._/#-]*$', "Enter the event report's number as your event reporting system shows it, without spaces.")])),
                ('report_due_on', models.DateField(blank=True, editable=False, help_text='The 10th work day after aware_on while the incident has a clock (services only)', null=True)),
                ('reportable', models.BooleanField(blank=True, null=True)),
                ('basis', models.CharField(blank=True, choices=[('may_have', 'The information reasonably suggests the device may have caused or contributed (use error included), or it cannot be ruled out'), ('not_serious', 'Not a death or serious injury as 21 CFR 803 defines it'), ('no_suggestion', 'The information does not suggest the device caused or contributed'), ('not_patient', 'The person was not a patient of the facility or staff on duty')], max_length=20)),
                ('decided_on', models.DateField(blank=True, null=True)),
                ('decided_by', models.CharField(blank=True, choices=[('risk', 'Risk management or patient safety'), ('committee', 'A safety or MDR committee'), ('ce', 'Clinical Engineering')], max_length=20)),
                ('fda_reported_on', models.DateField(blank=True, null=True)),
                ('manufacturer_reported_on', models.DateField(blank=True, null=True)),
                ('report_number', models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator('^\\d{10}-\\d{4}-\\d{4}$', "Enter the report number as 21 CFR 803 forms it: the facility's 10-digit number, the year, and a 4-digit sequence (0123456789-2026-0001).")])),
                ('finding', models.CharField(blank=True, choices=[('device_failure', 'Device failure or malfunction found'), ('accessory_failure', 'Failure found in an accessory, disposable, or connected device'), ('utility', 'A power, medical gas, or other utility problem found'), ('met_specs', 'The device met its specifications (no device fault found)'), ('manufacturer', 'Evaluated by the manufacturer'), ('not_evaluated', 'Could not be evaluated')], max_length=20)),
                ('accessories', models.CharField(blank=True, choices=[('kept', 'Kept with the device'), ('none_used', 'None were in use'), ('not_available', 'Not available (discarded or lost)')], help_text='The disposables and accessories in use, kept with the device as evidence', max_length=20)),
                ('event_log', models.CharField(blank=True, choices=[('saved', 'Saved'), ('no_log', 'The device keeps no log'), ('lost', 'Lost or could not be retrieved')], help_text="The device's event log", max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open'), ('closed', 'Closed'), ('in_error', 'Recorded in error')], default='open', max_length=10)),
                ('closed_on', models.DateField(blank=True, null=True)),
                ('asset', models.ForeignKey(help_text='The device suspected', on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='equipment.asset')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('recorded_by', models.ForeignKey(blank=True, help_text='Who recorded the decision in Cadence', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('work_order', models.ForeignKey(blank=True, help_text='The investigation: the request it was reported as (adopted), or one the incident opened', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidents', to='workorders.workorder')),
            ],
            options={
                'ordering': ['-occurred_on', '-number'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalIncidentHold',
            fields=[
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(blank=True, editable=False)),
                ('updated_at', models.DateTimeField(blank=True, editable=False)),
                ('held_on', models.DateField()),
                ('status_before', models.CharField(choices=[('in_service', 'In service'), ('in_repair', 'In repair'), ('out_of_service', 'Out of service'), ('on_loan', 'On loan'), ('missing', 'Missing'), ('retired', 'Retired')], help_text="The device's status when held (in_error restores it)", max_length=20)),
                ('sent_on', models.DateField(blank=True, help_text='Sent to the manufacturer for evaluation', null=True)),
                ('back_on', models.DateField(blank=True, help_text='Back from the manufacturer', null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('release', models.CharField(blank=True, choices=[('return_to_use', 'Returned to use'), ('keep_out', 'Kept out of service'), ('kept_by_manufacturer', 'Kept by the manufacturer'), ('in_error', 'Recorded in error')], max_length=30)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('asset', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='equipment.asset')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('released_by', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='tenants.tenant')),
                ('incident', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='incidents.incident')),
            ],
            options={
                'verbose_name': 'historical incident hold',
                'verbose_name_plural': 'historical incident holds',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='IncidentHold',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('held_on', models.DateField()),
                ('status_before', models.CharField(choices=[('in_service', 'In service'), ('in_repair', 'In repair'), ('out_of_service', 'Out of service'), ('on_loan', 'On loan'), ('missing', 'Missing'), ('retired', 'Retired')], help_text="The device's status when held (in_error restores it)", max_length=20)),
                ('sent_on', models.DateField(blank=True, help_text='Sent to the manufacturer for evaluation', null=True)),
                ('back_on', models.DateField(blank=True, help_text='Back from the manufacturer', null=True)),
                ('released_on', models.DateField(blank=True, null=True)),
                ('release', models.CharField(blank=True, choices=[('return_to_use', 'Returned to use'), ('keep_out', 'Kept out of service'), ('kept_by_manufacturer', 'Kept by the manufacturer'), ('in_error', 'Recorded in error')], max_length=30)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incident_holds', to='equipment.asset')),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holds', to='incidents.incident')),
                ('released_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
            ],
            options={
                'ordering': ['held_on', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'status'], name='incidents_i_tenant__ca0bf8_idx'),
        ),
        migrations.AddIndex(
            model_name='incident',
            index=models.Index(fields=['tenant', 'occurred_on'], name='incidents_i_tenant__bb3b0c_idx'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(fields=('tenant', 'number'), name='uniq_incident_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='incident',
            constraint=models.UniqueConstraint(condition=models.Q(('report_number', ''), _negated=True), fields=('tenant', 'report_number'), name='uniq_incident_report_number_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='incidenthold',
            constraint=models.UniqueConstraint(fields=('incident', 'asset'), name='uniq_incident_hold_per_device'),
        ),
    ]
