# Generated by Django 5.2.17 on 2026-10-05 14:55

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignments', models.BooleanField(default=True, help_text='Email me when a work order is assigned to me')),
                ('daily_digest', models.BooleanField(default=False, help_text='Email me each morning: my work orders due or overdue, and my PMs this week')),
                ('contract_reminders', models.BooleanField(default=True, help_text='Email me when a service contract is about to end (Contracts Edit)')),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('tenant', 'user'), name='uniq_notification_preference_per_user')],
            },
        ),
        migrations.CreateModel(
            name='NotificationSent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('assignment', 'Work order assigned'), ('digest', 'Daily digest'), ('contract', 'Contract ending')], max_length=20)),
                ('key', models.CharField(help_text='What it was about: a work order and its assignment, a day, a contract and its threshold', max_length=120)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('tenant', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='tenants.tenant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-sent_at'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'kind', 'key', 'user'), name='uniq_notification_sent')],
            },
        ),
    ]
