# Generated by Django 5.2.17 on 2026-10-08 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_historicalnotificationpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalnotificationpreference',
            name='incidents',
            field=models.BooleanField(default=True, help_text='Email me when an incident may need a report to the FDA or the manufacturer, and as its due date nears (Incidents Approve)'),
        ),
        migrations.AddField(
            model_name='notificationpreference',
            name='incidents',
            field=models.BooleanField(default=True, help_text='Email me when an incident may need a report to the FDA or the manufacturer, and as its due date nears (Incidents Approve)'),
        ),
        migrations.AlterField(
            model_name='notificationsent',
            name='kind',
            field=models.CharField(choices=[('assignment', 'Work order assigned'), ('digest', 'Daily digest'), ('contract', 'Contract ending'), ('incident', 'Incident report due')], max_length=20),
        ),
    ]
